package ninja.burpsuite.extension.sharpener.capabilities.objects;

public enum CapabilityGroup {
    AUDIT_ISSUE_HANDLER,
    CONTEXT_MENU_ITEMS_PROVIDER,
    HTTP_HANDLER,
    HTTP_REQUEST_EDITOR_PROVIDER,
    HTTP_RESPONSE_EDITOR_PROVIDER,
    INSERTION_POINT_PROVIDER,
    MESSAGE_HANDLER,
    PAYLOAD_GENERATOR_PROVIDER,
    PAYLOAD_PROCESSOR,
    PROXY_MESSAGE_HANDLER,
    PROXY_REQUEST_HANDLER,
    PROXY_RESPONSE_HANDLER,
    SCAN_CHECK,
    SCOPE_CHANGE_HANDLER,
    SESSION_HANDLING_ACTION,
    UNLOADING_HANDLER,
    WEBSOCKET_CREATION_HANDLER,
    WEBSOCKET_MESSAGE_EDITOR_PROVIDER,
    OTHER
}
